def generate_release_notes(commits):

    """
    Accepts:
    - list[str]
    - OR list[dict] (your current pipeline)
    """

    if not commits:
        return "No commits provided for release notes."

    cleaned = []

    for c in commits:

        # ---------------- STRING ----------------
        if isinstance(c, str):
            cleaned.append(c)

        # ---------------- DICT ----------------
        elif isinstance(c, dict):
            cleaned.append(
                c.get("summary")
                or c.get("message")
                or str(c)
            )

        # ---------------- FALLBACK ----------------
        else:
            cleaned.append(str(c))

    commits_text = "\n".join(cleaned)

    return f"""
📋 RELEASE NOTES

Changes in this release:

{commits_text}

---
Auto-generated by AI Engineering Productivity Platform
"""