def generate_summary(commit_messages):

    """
    Accepts:
    - list[str]
    - OR list[dict] (your current broken case)

    Returns clean sprint summary safely.
    """

    if not commit_messages:
        return "No commits provided for summary."

    cleaned_messages = []

    for c in commit_messages:

        # ---------------- CASE 1: string ----------------
        if isinstance(c, str):
            cleaned_messages.append(c)

        # ---------------- CASE 2: dict ----------------
        elif isinstance(c, dict):
            cleaned_messages.append(
                c.get("summary")
                or c.get("message")
                or str(c)
            )

        # ---------------- CASE 3: fallback ----------------
        else:
            cleaned_messages.append(str(c))

    commits_text = "\n".join(cleaned_messages)

    summary = f"""
📝 SPRINT SUMMARY

Total Items: {len(cleaned_messages)}

Key Changes:
------------------------
{commits_text}

------------------------
Auto-generated by AI Engineering Productivity Platform
"""

    return summary